[phases.setup]
nixPkgs = ["nodejs_24", "pnpm", "unzip", "gnutar"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
cmd = "pnpm db:migrate:prod && pnpm start"
